#POST /api/v1/tasks HTTP/1.1
#Host: localhost:8080
#Content-Type: application/json
#
#{
#  "title": "Sample Title",
#  "description": "Sample description of the object",
#  "userId": 12345
#}


PUT /api/v1/tasks/1452 HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
  "id": 1452,
  "title": "Sample Title",
  "description": "new description",
  "status": "CLOSED",
  "userId": 12345
}