spring:
  application:
    name: java-project-t1
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        cache:
          use_second_level_cache: true
          use_query_cache: true
          region:
            factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
  liquibase:
    enabled: true
    change-log: classpath:db.changelog-master.yaml

jwt:
  secret-key: okay
  access-token-expiration: 600
  refresh-token-expiration: 3600

logging:
  level:
    root: info
    ru.t1.school.open.project: info
    org.apache.kafka.clients.consumer: info

t1:
  root-path: ru.t1.school.open.project
  kafka:
    bootstrap:
      servers: 127.0.0.1:29092
    topic:
      task: tp_project_t1_tasks
    producer:
      enabled: true
    consumer:
      group-id: tp-project-t1
      session:
        timeout-ms: 30000
      heartbeat-interval-ms: 10000
      max-partition-fetch-bytes: 100000
      poll-timeout-ms: 5000
      max-poll-records: 2
      max-poll-interval-ms: 10000
    listener:
      poll-timeout: 100

t1-starter:
  logger:
    level: SHORT
