spring:
  application:
    name: java-project-t1
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
logging:
  level:
#    root: info
    ru.t1.school.open.project: info